spring:
  h2:
    console: 
      path: /console
      enabled: true

  multi-datasource:
    basePackages: org.sbcoba.springboot.multidatasource.sample.service
    default-datasource-name: db1
    datasources:
      db1:
        url: jdbc:h2:~/db1;
        data: classpath:db1Data.sql
      db2:
        url: jdbc:h2:~/db2;
        data: classpath:db2Data.sql
      db3:
        url: jdbc:h2:~/db3;
        data: classpath:db3Data.sql
      db4:
        url: jdbc:h2:~/db4;
        data: classpath:db4Data.sql

logging:
  level:
    org.springframework:
      boot: DEBUG
      transaction: DEBUG
    org.sbcoba.springboot.multidatasource: DEBUG

